In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 8.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.3 MB 6.9 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 7.7 MB/s eta 0:00:02
   ----------------- ---------------------- 5.2/12.3 MB 7.4 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.3 MB 6.9 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.3 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 7.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 7.0 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [8]:
#1D array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) #dimension of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1, 5) # 1 row and 5 columns 

array([[1, 2, 3, 4, 5]])

In [15]:
arr3=np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr3.shape)

(2, 5)


In [19]:
np.arange(0, 10, 2).reshape(1, 5)

array([[0, 2, 4, 6, 8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr4=np.array([[1,2,3], [4,5,6]])
print(arr4.shape) #shape of array
print(arr4.ndim) #row dimn
print(arr4.size) #no of elements
print(arr4.dtype) #element data type
print(arr4.itemsize) #size of element

(2, 3)
2
6
int64
8


In [24]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([-1,-2,-3,-4,-5])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[0 0 0 0 0]
[ 2  4  6  8 10]
[ -1  -4  -9 -16 -25]
[-1. -1. -1. -1. -1.]


In [26]:
#universal functions
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
